version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend_net

  backend:
    image: ${kaushalchauhan84850}/student-backend:${IMAGE_TAG:-latest}
    container_name: backend
    restart: always
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/studentdb
      - APP_ENV=${APP_ENV:-dev}
    ports:
      - "5000:5000"
    networks:
      - backend_net

volumes:
  mongo_data:

networks:
  backend_net:
    driver: bridge
