services:
  backend:
    build: .
    image: ${DOCKERHUB_USERNAME:-local}/student-backend:${IMAGE_TAG:-latest}
    container_name: backend
    restart: always
    environment:
      - PORT=5000
      # Set this to your MongoDB Atlas (or other managed Mongo) connection string
      - MONGO_URI=${secrets.MONGO_URI}
      - APP_ENV=${APP_ENV:-dev}
    ports:
      - "5000:5000"
