project_id          = "prod-infra-503304"
environment         = "prod"
region              = "asia-south1"
zone                = "asia-south1-a"
machine_type        = "e2-medium"
dockerhub_username  = "kaushalchauhan84850"
image_tag           = "prod"
